// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ChangeSecurePassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ChatAppendSessionLine(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ChatDeleteSession(arg1:string,arg2:string):Promise<void>;

export function ChatListSessionIDs(arg1:string):Promise<Array<string>>;

export function ChatReadSessionFile(arg1:string,arg2:string):Promise<string>;

export function ChatReadSessionMeta(arg1:string,arg2:string):Promise<string>;

export function ChatRenameSession(arg1:string,arg2:string,arg3:string):Promise<backend.ChatSessionMetadata>;

export function ChatWriteSessionMeta(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DecryptNote(arg1:string,arg2:string):Promise<string>;

export function EncryptNote(arg1:string,arg2:string,arg3:string):Promise<backend.ScannedNote>;

export function GetSettings():Promise<backend.Settings>;

export function ProviderApiKeyDelete(arg1:string):Promise<void>;

export function ProviderApiKeyList():Promise<Array<string>>;

export function ProviderApiKeyLoad(arg1:string):Promise<any>;

export function ProviderApiKeySave(arg1:string,arg2:string):Promise<void>;

export function UnlockSecure(arg1:string,arg2:string):Promise<void>;

export function UpdateSettings(arg1:backend.Settings):Promise<void>;

export function VaultDeleteFile(arg1:string,arg2:string):Promise<void>;

export function VaultPickFolder():Promise<string>;

export function VaultReadFile(arg1:string,arg2:string):Promise<string>;

export function VaultRenameFile(arg1:string,arg2:string,arg3:string):Promise<backend.ScannedNote>;

export function VaultScan(arg1:string):Promise<Array<backend.ScannedNote>>;

export function VaultStartWatching(arg1:string):Promise<void>;

export function VaultStopWatching():Promise<void>;

export function VaultWriteFile(arg1:string,arg2:string,arg3:string):Promise<number>;
