// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeSecurePassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangeSecurePassword'](arg1, arg2, arg3);
}

export function ChatAppendSessionLine(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatAppendSessionLine'](arg1, arg2, arg3);
}

export function ChatDeleteSession(arg1, arg2) {
  return window['go']['main']['App']['ChatDeleteSession'](arg1, arg2);
}

export function ChatListSessionIDs(arg1) {
  return window['go']['main']['App']['ChatListSessionIDs'](arg1);
}

export function ChatReadSessionFile(arg1, arg2) {
  return window['go']['main']['App']['ChatReadSessionFile'](arg1, arg2);
}

export function ChatReadSessionMeta(arg1, arg2) {
  return window['go']['main']['App']['ChatReadSessionMeta'](arg1, arg2);
}

export function ChatRenameSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatRenameSession'](arg1, arg2, arg3);
}

export function ChatWriteSessionMeta(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatWriteSessionMeta'](arg1, arg2, arg3);
}

export function DecryptNote(arg1, arg2) {
  return window['go']['main']['App']['DecryptNote'](arg1, arg2);
}

export function EncryptNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['EncryptNote'](arg1, arg2, arg3);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ProviderApiKeyDelete(arg1) {
  return window['go']['main']['App']['ProviderApiKeyDelete'](arg1);
}

export function ProviderApiKeyList() {
  return window['go']['main']['App']['ProviderApiKeyList']();
}

export function ProviderApiKeyLoad(arg1) {
  return window['go']['main']['App']['ProviderApiKeyLoad'](arg1);
}

export function ProviderApiKeySave(arg1, arg2) {
  return window['go']['main']['App']['ProviderApiKeySave'](arg1, arg2);
}

export function UnlockSecure(arg1, arg2) {
  return window['go']['main']['App']['UnlockSecure'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function VaultDeleteFile(arg1, arg2) {
  return window['go']['main']['App']['VaultDeleteFile'](arg1, arg2);
}

export function VaultPickFolder() {
  return window['go']['main']['App']['VaultPickFolder']();
}

export function VaultReadFile(arg1, arg2) {
  return window['go']['main']['App']['VaultReadFile'](arg1, arg2);
}

export function VaultRenameFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['VaultRenameFile'](arg1, arg2, arg3);
}

export function VaultScan(arg1) {
  return window['go']['main']['App']['VaultScan'](arg1);
}

export function VaultStartWatching(arg1) {
  return window['go']['main']['App']['VaultStartWatching'](arg1);
}

export function VaultStopWatching() {
  return window['go']['main']['App']['VaultStopWatching']();
}

export function VaultWriteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['VaultWriteFile'](arg1, arg2, arg3);
}
