name: Wails build

on:
  push:
    tags:
      - 'v*'

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: 'nook', platform: 'linux/amd64', os: 'ubuntu-latest', nsis: false},
          {name: 'nook', platform: 'linux/arm64', os: 'ubuntu-latest', nsis: false},
          {name: 'nook', platform: 'windows/amd64', os: 'windows-latest', nsis: true},
          {name: 'nook', platform: 'windows/arm64', os: 'windows-latest', nsis: true},
          {name: 'nook', platform: 'darwin/universal', os: 'macos-latest', nsis: false}
        ]
    runs-on: ${{ matrix.build.os }}
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build wails
      uses: snider/build/actions/build/wails2@v3
      with:
        build-name: ${{ matrix.build.name }}
        build-platform: ${{ matrix.build.platform }}
        package: true
        go-version: '1.23'
        nsis: ${{ matrix.build.nsis }}
